.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PHPENV\-INSTALL\.SH" "1" "October 2011" "" ""
.
.SH "NAME"
\fBphpenv\-install\.sh\fR \- Sets up a separate rbenv environment for PHP
.
.SH "SYNOPSIS"
\fBphpenv\-install\.sh\fR
.
.SH "DESCRIPTION"
The phpenv\-install\.sh command sets up a separate rbenv environment for usage with PHP\. This environment is stored in the \fB$HOME/\.phpenv\fR directory and contains a \fBphpenv\fR executable which sets the \fBRBENV_ROOT\fR environment variable to \fB$HOME/\.phpenv\fR\.
.
.P
The \fBphpenv\-install\.sh\fR command has an optional "update" mode which updates the \fB$HOME/\.phpenv\fR to the latest source code from the rbenv repository and creates a new \fBphpenv\fR executable\. This mode is triggered by setting the \fBUPDATE\fR environment variable before calling \fBphpenv\-install\.sh\fR, for example:
.
.IP "" 4
.
.nf

$ UPDATE=yes phpenv\-install\.sh
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
rbenv \fIhttp://github\.com/sstephenson/rbenv\fR
